{"uuid": "8923c40e-36ca-4d17-a652-a142cc64f333", "children": ["f83fd5b4-99e1-4ec5-a775-7a4b28628cef"], "befores": [{"name": "_xunit_setup_method_fixture_TestSocialMedia", "status": "passed", "start": 1717841366626, "stop": 1717841373119}], "afters": [{"name": "_xunit_setup_method_fixture_TestSocialMedia::0", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"C:\\Users\\90552\\Desktop\\sunum\\tobeto\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\90552\\Desktop\\sunum\\tobeto\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 893, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\90552\\Desktop\\sunum\\tobeto\\.venv\\Lib\\site-packages\\_pytest\\python.py\", line 824, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"C:\\Users\\90552\\Desktop\\sunum\\tobeto\\.venv\\Lib\\site-packages\\_pytest\\python.py\", line 716, in _call_with_optional_argument\n    func()\n  File \"C:\\Users\\90552\\Desktop\\sunum\\tobeto\\tests\\test_social_media.py\", line 20, in teardown_method\n    self.driver.quit()\n  File \"C:\\Users\\90552\\Desktop\\sunum\\tobeto\\.venv\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 193, in quit\n    self.service.stop()\n  File \"C:\\Users\\90552\\Desktop\\sunum\\tobeto\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 146, in stop\n    self.send_remote_shutdown_command()\n  File \"C:\\Users\\90552\\Desktop\\sunum\\tobeto\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 131, in send_remote_shutdown_command\n    if not self.is_connectable():\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\90552\\Desktop\\sunum\\tobeto\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 120, in is_connectable\n    return utils.is_connectable(self.port)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\90552\\Desktop\\sunum\\tobeto\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\utils.py\", line 101, in is_connectable\n    socket_ = socket.create_connection((host, port), 1)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\90552\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\socket.py\", line 844, in create_connection\n    exceptions.clear()  # raise only the last error\n    ^^^^^^^^^^^^^^^^^^\n"}, "start": 1717841398196, "stop": 1717841400379}], "start": 1717841366626, "stop": 1717841400379}